# Site settings
title: "Daniel Toranzo Pérez"
description: "Daniel Toranzo Pérez curriculum vitae."
google-verification: "r8LavZ7oFRU_3YLmlH7wSHXuTdIikA0FXh9M_2xaE4E"
author: "Daniel Toranzo Pérez"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Daniel Toranzo Pérez"
resume_title:                   "Ingeniero de software"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "daniel@obocat.com"

display_header_contact_info:    "false"

resume_header_intro: "<p>Me interesan los temas relacionados con el procesamiento paralelo, arquitecturas heterogéneas y la eficiencia de los algoritmos. Me gusta 
aprender cosas nuevas, trabajar en equipo y tengo facilidad para adaptarme a las situaciones que se me presenten aplicando el enfoque de la ingeniería.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_certifications:  true
show_appstore_banner:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://obocat.github.io/daniel_toranzo_perez/"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/daniel-toranzo-pérez/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

